server:
  port: 8080

logging:
  file:
    path: logs/
  level:
    com.zaxxer.hikari.util.DriverDataSource: ERROR
    org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: ERROR
    org.apache.kafka.clients.NetworkClient: ERROR
    # com.valhalla.runnable: DEBUG

spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:clickhouse://localhost:8123?rewriteBatchedStatements=true
    # username: root
    # password: root
    # 确保jdbc驱动的jar在driver目录下
    # mysql com.mysql.cj.jdbc.Driver
    # clickhouse com.clickhouse.jdbc.ClickHouseDriver
    driverClassName: com.clickhouse.jdbc.ClickHouseDriver
    hikari:
      maximumPoolSize: 20
      minimumIdle: 5
      idleTimeout: 30000
      poolName: HikariCP
      maxLifetime: 600000
      connectionTimeout: 30000

mqtt:
  host: tcp://localhost:1883
  clientId: generic-jdbc-writer
  # username:
  # password:

kafka:
  servers: 0.0.0.0:9094
  groupId: generic-jdbc-writer
  # should be false
  enableAutoCommit: false
  autoCommitInterval: 5_000
  autoOffsetReset: false
  maxPollRecords: 500
  cycleTime: 500
  maxPollInterval: 1000
  heartbeatInterval: 15_000
  sessionTimeout: 180_000
  reconnectBackoff: 10_000
  maxReconnectBackoff: 30_000